# Workflow to associate labels automatically
name: prchecking
# Trigger the workflow on pull request events
on:
  pull_request:
    branches: [ develop, master, release ]
    types:
      # Check title when opened.
      - opened
      # Check title when new commits are pushed.
      # Required to use as a status check.
      - synchronize
      - edited
jobs:
  prchecking:
    runs-on: ubuntu-18.04
    steps:
      # We need to checkout the repository to access the configured file (.github/label-pr.yml)
      - uses: actions/checkout@v2
      - name: Labeler
        id: labeler
        uses: docker://decathlon/pull-request-labeler-action:2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Here we can override the path for the action configuration. If none is provided, default one is `.github/label-pr.yml`
          CONFIG_PATH: ${{ secrets.GITHUB_WORKSPACE }}/.github/label-pr.yml
        continue-on-error: true
      - uses: deepakputhraya/action-pr-title@master
        id: pr_title
        with:
          # Match pull request titles in the start of US1234 or DE1234 or TA1234.
          regex: '^(US|DE|TA)\d* '
          github_token: ${{ github.token }}
        continue-on-error: true
      - run: mkdir -p output/
      - run: |
          echo "PR checking false." > output/results.txt
      - name: comment PR
        uses: machine-learning-apps/pr-comment@master
        if: steps.pr_title.outcome != 'success' || steps.labeler.outcome != 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: output/results.txt
